### ISSUE TITLE
Cross-chain transfer example using PactSharp

### ISSUE THREAD

**Issue by oliverw** [hexafluoride/Shadena#2]
(would have filed this under discussions, if the feature would be enabled for the repo 😄 )

Could you provide a bit of guidance on how to perform a Kadena Transfer with `coin.transfer-crosschain` using PactSharp?

**Comment by hexafluoride** [comment]
Crosschain transactions need to go through the (somewhat hidden) SPV endpoint. I will definitely add support for this at some point, hopefully soon!

**Comment by oliverw** [comment]
> Crosschain transactions need to go through the (somewhat hidden) SPV endpoint. I will definitely add support for this at some point, hopefully soon!

Thanks. Good to know. I think this can be closed and solved online in discord.

**Comment by hexafluoride** [comment]
This has been implemented in PactSharp and Shadena, see [CompleteCrosschain.razor](https://github.com/hexafluoride/Shadena/blob/main/Shadena/Pages/CompleteCrosschain.razor) for some example code.
