### ISSUE TITLE
Autocomplete improvements 

### ISSUE THREAD

**Issue by JCM00N** [hexafluoride/Shadena#6]
I think the editors' autocomplete feature is very important for pact developers ux. I have a couple of suggestions for its' enhancement.

- Have the autocomplete categorize different types (functions, variables, modules etc.).
- Add basic documentation to the autocomplete suggestions (basic types for functions, description for built ins...)
- Since this is based off of the Monaco editor, I wonder how complex it'd be to port it over to vscode. I believe having pact intellisense on vscode would make Pact much more accessible. There is an [extension for syntax highlighting](https://github.com/floordebest/pact-vscode), but it has some issues:
![syntax-issue](https://user-images.githubusercontent.com/106163790/170470770-5b17d16c-9f07-4f3c-93b2-6c045de59164.png)

I'm not familiar with the way Lexical analysis works with Monaco / Monarch, but am learning it and will be glad to offer assistance in order to implement these.

**Comment by hexafluoride** [comment]
There is an experiment I did that involved writing a Pact parser, you can find the relevant code in the [parser](https://github.com/hexafluoride/Shadena/tree/parser) branch. I did not quite take it to its conclusion, but I did get scope-relevant identifier autocomplete suggestions working. If you are interested in continuing that work, or using it as a reference, that'd be great and I'd be happy to review your code :)

**Comment by JCM00N** [comment]
I looked into it a bit more, and... yeah. Writing a parser by hand is quite rough. I think a better alternative would be to use ANTLR.

**Comment by hexafluoride** [comment]
For sure, the ad-hoc parser lacks some niceties that would be present with a parser framework. Again, I'll be happy to review and provide feedback on any work, but I currently don't have the time to devote to this feature. If you do decide to contribute, just ping me on any change! Thanks for understanding :)

**Comment by hexafluoride** [comment]
Closing as not planned for now, feel free to reopen if any activity is planned on this.
